name 'dbserver'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures dbserver'
long_description 'Installs/Configures dbserver'
version '0.1.0'
