name 'build-base'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures build-base'
long_description 'Installs/Configures build-base'
version '0.1.0'
